[tool.black]
line-length = 88
target-version = ['py311']


[tool.pylint.MASTER]
ignore-patterns = ['venv/*', 'pycache/*', 'recommendation_system.py']
init-hook = 'import sys; sys.path.append(".")' # Fixes import errors in pylint
disable = [
    'C0103', # Invalid variable name
    'C0301', # Constant check
    'R0902', # Too many instance attributes
    'R0903', # Too few public methods
    'R0904', # Too many public methods
    'R0911', # Too many return statements
    'R0913', # Too many arguments
    'C0302', # Too many lines in module
    'R1705', # Unnecessary "else" after "return"
    'W0105', # String statement has no effect
    'W0612', # Unused variable
]


[tool.mypy]
python_version = '3.11'

[[tool.mypy.overrides]]
module = 'flask_login'
ignore_missing_imports = true # No typing support for flask_login

[[tool.mypy.overrides]]
module = 'flask_mail'
ignore_missing_imports = true # No typing support for flask_mail

[[tool.mypy.overrides]]
module = 'yfinance'
ignore_missing_imports = true # No typing support for yfinance

[[tool.mypy.overrides]]
module = 'sklearn.linear_model'
ignore_missing_imports = true # No typing support for sklearn.linear_model

[[tool.mypy.overrides]]
module = 'sklearn.metrics'
ignore_missing_imports = true # No typing support for sklearn.metrics

[[tool.mypy.overrides]]
module = 'sklearn.model_selection'
ignore_missing_imports = true # No typing support for sklearn.model_selection

[[tool.mypy.overrides]]
module = 'database.*'
follow_imports = 'skip' # Prevent mypy from checking database twice

[[tool.mypy.overrides]]
module = 'linear_regression.*'
follow_imports = 'skip' # Prevent mypy from checking linear_regression twice

[[tool.mypy.overrides]]
module = 'nltk.*'
ignore_missing_imports = true # No typing support for nltk

[[tool.mypy.overrides]]
module = 'sumy.*'
ignore_missing_imports = true # No typing support for sumy

[[tool.mypy.overrides]]
module = 'sklearn.*'
ignore_missing_imports = true # No typing support for sklearn

[[tool.mypy.overrides]]
module = 'newsapi'
ignore_missing_imports = true # No typing support for newsapi

[[tool.mypy.overrides]]
module = 'newspaper'
ignore_missing_imports = true # No typing support for newspaper


[tool.ruff]
target-version = 'py311'
# Defaults + pyflakes + pycodestyle + pylint + isort
lint.select = ['ALL']
# Ignore conflicting docstring errors
lint.ignore = ['ANN101', 'D203', 'D204', 'D205', 'D213', 'D401', 'D415']
exclude = [
    "recommendation_system.py",
]


[tool.ruff.lint.pylint]
max-args = 9

[tool.ruff.lint.per-file-ignores]
"db.py" = [
    'E501', # Line too long
]
"index.py" = [
    'S105', # Hardcoded password
    'PLR0911', # Too many return statements
    'T201', # Use of print statement
]
"database/database_connection.py" = [
    'E501', # Line too long
]
"database/db_schema.py" = [
    'E501', # Line too long
    'PLR0913', # Too many arguments
    'ERA001', # Commented out code
    'T201', # Use of print statement
]
"database/mock_article_objects.py" = [
    'E501', # Line too long
]
"database/extract_news_script.py" = [
    'E501', # Line too long
    'ERA001', # Commented out code
    'T201', # Use of print statement
]
"database/search_component.py" = [
    'E501', # Line too long
    'ERA001', # Commented out code
    'T201', # Use of print statement
]
"database/tf_idf.py" = [
    'E501', # Line too long
    'ERA001', # Commented out code
]
"database/text_summariser.py" = [
    'ERA001', # Commented out code
]
"linear_regression/capm.py" = [
    'T201', # Use of print statement
]
"linear_regression/linear_regression.py" = [
    'T201', # Use of print statement
    'N803', # Argument name should be lowercase
    'ERA001', # Commented out code
    'N806', # Variable in function should be lowercase
    'F841', # Unused variable
]