name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv and dependencies
        run: |
          cd tradetalker/api
          pip install --user pipenv
          pipenv install --dev --deploy

  check:
    name: Check code quality
    runs-on: ubuntu-latest
    needs: install
    if: success()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pipenv and dependencies
        run: |
          cd tradetalker/api
          pip install --user pipenv
          pipenv install --dev --deploy

      - name: Run black formatting check
        run: |        
          cd tradetalker/api
          pipenv run black . --check --diff

      - name: Run pylint check
        run: |
          cd tradetalker/api
          pipenv run pylint . --fail-under=10

      - name: Run ruff check
        run: |
          cd tradetalker/api
          pipenv run ruff check .

      - name: Run mypy type check
        run: |
          cd tradetalker/api
          pipenv run mypy . --verbose
