name: Backend checks

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          pip install flake8
          cd tradetalker/api
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install pylint
        run: |
          source venv/bin/activate
          pip install pylint

      - name: Run flake8
        run: flake8 tradetalker/api --count --show-source --statistics

      - name: Run pylint
        run: |
          pylint --version
          which pylint
          source venv/bin/activate
          pylint tradetalker/api --fail-under=10
