name: Backend checks

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          cd tradetalker/api
          python3 -m venv venv
          source venv/bin/activate
          pip install flake8 pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flake8
        run: |
          cd tradetalker/api
          source venv/bin/activate
          flake8 . --count --show-source --statistics

      - name: Run pylint
        run: |
          cd tradetalker/api
          source venv/bin/activate
          pylint . --fail-under=10
