name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '>=21.0.0'

      - name: Install npm dependencies
        run: |
          cd tradetalker
          npm install

      - name: Install pnpm dependencies
        run: |
          cd tradetalker
          npm install -g pnpm
          pnpm install

      - name: Run ESLint
        run: |
          cd tradetalker
          npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier
        run: |
          cd tradetalker
          npx prettier . --check
